language: c

#os:
# - linux
# - osx

compiler:
  - gcc
  - clang
  
env: KVZ_DISABLE_AVX2=1 

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y yasm
  - sudo apt-get install -qq gcc-4.8

script: 
  - cd src
  - make
  - if [ "$CC" = "gcc" ]; then make clean && export CC=gcc-4.8 && make; fi
  