language: c

# Use container based infrastructure.
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - gcc-4.8
      - libtool
      - valgrind
      - yasm

matrix:
  fast_finish: true

  include:
    - compiler: clang
    - compiler: gcc-4.8

    # We have some Mac specific code and Mac sometimes has odd build issues.
    - os: osx
      compiler: clang  # gcc is actually clang on Travis OS X
      install: true
      script:
        - ./autogen.sh
        - ./configure --enable-werror
        - make --jobs=2 V=1

install: bash .travis-install.bash

script:
  - ./autogen.sh
  - ./configure --enable-werror
  - make --jobs=2 V=1
  - make check KVZ_TEST_VALGRIND=1 VERBOSE=1

after_script:
  # Disable errors to work around Travis not knowing how to fix their stuff.
  - set +e
