language: c

#os:
# - linux
# - osx

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y yasm
  - sudo apt-get install -qq gcc-4.8

script: 
  - cd src
  - export KVZ_DISABLE_AVX2=1 
  - make
  - if [ "$CC" = "gcc" ]; then make clean && unset KVZ_DISABLE_AVX2 && export CC=gcc-4.8 && make; fi
  